### ISSUE TITLE
Geo Data Class (Stylable Layer Set) URIs

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-styles#13]
See https://github.com/opengeospatial/NamingAuthority/issues/97

**Comment by jeffharrison** [comment]
During June 1 2021 SWG mtg group noted that the Code Sprint did not do testing on this Issue. 

Some of the discussion from June 1 2021 SWG mtg included...

SWG recommends that we (still) need to find a better designator for this than "Stylable Layer Set".

Specifically, this is an "Encoding of Data Conforming to an Application Schema that can be Styled". For example, OS Zoomstack has vector tiles and GPKG encodings with slightly different FeatureTypes, but they are both representing the same Application Schema.

Additional discussion required.

**Comment by jeffharrison** [comment]
SWG discussed this on 13 July 2021. The example of OS Zoomstack with vector tiles and GPKG 'distributions' of the same data was reviewed again. This situation may require two different URIs. One for vector tiles and one for GPKG distributions. 

This Issue is attempting to address generating or finding a stylesheet suitable for a particular purpose from the original stylesheet. This is also about a way to easily find stylesheets for your map. Let's say we have some TDS data from NSG, this capability will allow applications to discover stylesheets for vector tiles, shapefiles, GeoJSON etc representations. The challenge here is to establish a type of relation. 

From a Styles API perspective we could possibly have a general association 'tagging' mechanism. The implementation of this is straightforward. There is a standardized link relation type we could use. Clemens offered to create PR for this general 'tagging' mechanism. SWG will review during next meeting.
